### ISSUE TITLE
Simplify definition of counted parameters

### ISSUE THREAD

**Issue by VGPReys** [haddocking/haddock3#1029]
## **Desired feature/enhancement**

It would be simpler to compute on the fly some of the counted parameters.

## **Motivation**

Simplify the configuration files with unnecessary parameters

## **Description**

The idea is to go from:

```toml
[flexref]
nfle = 2    # Useless parameter, as we could compute it from the number of defined flexible segments.
fle_sta_1 = 1
fle_end_1 = 10
fle_seg_1 = "A"
fle_sta_2 = 1
fle_end_2 = 10
fle_seg_2 = "B"
```

to:

```toml
[flexref]
fle_sta_1 = 1
fle_end_1 = 10
fle_seg_1 = "A"
fle_sta_2 = 1
fle_end_2 = 10
fle_seg_2 = "B"
```
