### ISSUE TITLE
OpenMM Module- "Exception in task execution: 'NoneType' object is not iterable"

### ISSUE THREAD

**Issue by atroel01** [haddocking/haddock3#1153]
Fristly thanks for the great program and easy installation process.

## **OpenMM module**
Running Openmm module to refine top models:

Here is my full
```toml
run_dir = "haddock_files"
mode = "local"
ncores = 31
self_contained = true
postprocess = true
clean = true
molecules =  [
    "clean_ab.pdb",
    "clean_ag.pdb"
    ]

[topoaa]

[rigidbody]
sampling = 2000
randremoval = true
tolerance = 5
ambig_fname = "ambig.tbl"
unambig_fname = "ab_unambig.tbl"

[clustfcc]

[seletopclusts]
top_cluster = 10
top_models = 20

[flexref]
ambig_fname = "ambig.tbl"
unambig_fname = "ab_unambig.tbl"
randremoval = true

[emref]
ambig_fname = "ambig.tbl"
unambig_fname = "ab_unambig.tbl"
randremoval = true

[mdref]
ambig_fname = "ambig.tbl"
unambig_fname = "ab_unambig.tbl"
randremoval = true

[clustfcc]

#Contact map and alanine scanning
[seletopclusts]
top_cluster = 10
top_models = 10

[caprieval]
reference_fname = "5xmh_ref.pdb"

[seletopclusts]
top_cluster = 3
top_models = 3

[openmm]
forcefield = 'amber14/protein.ff14SB.xml'
explicit_solvent_model = 'amber14/tip3p.xml'
timestep_ps = 0.002
constraints = 'HBonds'
equilibration_timesteps = 1000
simulation_timesteps = 1000
```

## **Expected behavior**
Expecting refined model output

## **Actual behavior**
Run fine until step 11:

```text
[<time>__init__ INFO] [seletopclusts] took 0 seconds
[<time>__init__ INFO] Running [openmm] module
[<time>__init__ INFO] [openmm] Creating directory pdbfixer
[<time>__init__ INFO] [openmm] Creating directory solvation_boxes
[<time>__init__ INFO] [openmm] Creating directory intermediates
[<time>__init__ INFO] [openmm] Creating directory md_raw_output
[<time>__init__ INFO] [openmm] Creating directory openmm_output
[<time>__init__ INFO] [openmm] Creating directory simulation_stats
[<time>libutil INFO] Selected 9 cores to process 9 jobs, with 32 maximum available cores.
[<time>libparallel INFO] Using 9 cores
[<time>openmm INFO] Fixing pdb: cluster_1_model_1.pdb (path ../10_seletopclusts/cluster_1_model_1.pdb)
[<time>openmm INFO] Fixing pdb: cluster_1_model_2.pdb (path ../10_seletopclusts/cluster_1_model_2.pdb)
[<time>openmm INFO] Fixing pdb: cluster_1_model_3.pdb (path ../10_seletopclusts/cluster_1_model_3.pdb)
[<time>openmm INFO] Fixing pdb: cluster_2_model_1.pdb (path ../10_seletopclusts/cluster_2_model_1.pdb)
[<time>openmm INFO] Fixing pdb: cluster_2_model_2.pdb (path ../10_seletopclusts/cluster_2_model_2.pdb)
[<time>openmm INFO] Fixing pdb: cluster_2_model_3.pdb (path ../10_seletopclusts/cluster_2_model_3.pdb)
[<time>openmm INFO] Fixing pdb: cluster_3_model_1.pdb (path ../10_seletopclusts/cluster_3_model_1.pdb)
[<time>openmm INFO] Fixing pdb: cluster_3_model_2.pdb (path ../10_seletopclusts/cluster_3_model_2.pdb)
[<time>openmm INFO] Fixing pdb: cluster_3_model_3.pdb (path ../10_seletopclusts/cluster_3_model_3.pdb)
[<time>openmm INFO] Building solvation box for: cluster_1_model_3.pdb
[<time>openmm INFO] Building solvation box for: cluster_1_model_2.pdb
[<time>openmm INFO] Building solvation box for: cluster_2_model_1.pdb
[<time>openmm INFO] Building solvation box for: cluster_1_model_1.pdb
[<time>openmm INFO] Building solvation box for: cluster_2_model_3.pdb
[<time>openmm INFO] Building solvation box for: cluster_3_model_2.pdb
[<time>openmm INFO] Building solvation box for: cluster_3_model_3.pdb
[<time>openmm INFO] Building solvation box for: cluster_3_model_1.pdb
[<time>openmm INFO] Building solvation box for: cluster_2_model_2.pdb
[<time>openmm INFO] Solvating and adding ions to the system:padding 1.0 nm, ions conc. : 0.15 M
[<time>openmm INFO] Solvating and adding ions to the system:padding 1.0 nm, ions conc. : 0.15 M
[<time>openmm INFO] Solvating and adding ions to the system:padding 1.0 nm, ions conc. : 0.15 M
[<time>openmm INFO] Solvating and adding ions to the system:padding 1.0 nm, ions conc. : 0.15 M
[<time>openmm INFO] Solvating and adding ions to the system:padding 1.0 nm, ions conc. : 0.15 M
[<time>openmm INFO] Solvating and adding ions to the system:padding 1.0 nm, ions conc. : 0.15 M
[<time>openmm INFO] Solvating and adding ions to the system:padding 1.0 nm, ions conc. : 0.15 M
[<time>openmm INFO] Solvating and adding ions to the system:padding 1.0 nm, ions conc. : 0.15 M
[<time>openmm INFO] Solvating and adding ions to the system:padding 1.0 nm, ions conc. : 0.15 M
[<time>openmm INFO] Equilibrating solvation box from solvation_boxes/cluster_1_model_2.pdb...
[<time>openmm INFO] Equilibrating solvation box from solvation_boxes/cluster_1_model_3.pdb...
[<time>openmm INFO] Equilibrating solvation box from solvation_boxes/cluster_1_model_1.pdb...
[<time>openmm INFO] Equilibrating solvation box from solvation_boxes/cluster_3_model_3.pdb...
[<time>openmm INFO] Equilibrating solvation box from solvation_boxes/cluster_2_model_1.pdb...
[<time>openmm INFO] Equilibrating solvation box from solvation_boxes/cluster_3_model_1.pdb...
[<time>openmm INFO] Equilibrating solvation box from solvation_boxes/cluster_2_model_2.pdb...
[<time>openmm INFO] Equilibrating solvation box from solvation_boxes/cluster_3_model_2.pdb...
[<time>openmm INFO] Equilibrating solvation box from solvation_boxes/cluster_2_model_3.pdb...
[<time>openmm INFO] Adding protein constraints
[<time>openmm INFO] Adding protein constraints
[<time>openmm INFO] Adding protein constraints
[<time>openmm INFO] Adding protein constraints
[<time>openmm INFO] Adding protein constraints
[<time>openmm INFO] Adding protein constraints
[<time>openmm INFO] Adding protein constraints
[<time>openmm INFO] Adding protein constraints
[<time>openmm INFO] Adding protein constraints
[<time>openmm INFO] Minimizing system energy
[<time>openmm INFO] starting explicit solvent openMM simulation with file: None
[<time>libparallel WARNING] Exception in task execution: 'NoneType' object is not iterable
[<time>openmm INFO] Minimizing system energy
[<time>openmm INFO] starting explicit solvent openMM simulation with file: None
[<time>libparallel WARNING] Exception in task execution: 'NoneType' object is not iterable
[<time>openmm INFO] Minimizing system energy
[<time>openmm INFO] starting explicit solvent openMM simulation with file: None
[<time>libparallel WARNING] Exception in task execution: 'NoneType' object is not iterable
[<time>openmm INFO] Minimizing system energy
[<time>openmm INFO] starting explicit solvent openMM simulation with file: None
[<time>libparallel WARNING] Exception in task execution: 'NoneType' object is not iterable
[<time>openmm INFO] Minimizing system energy
[<time>openmm INFO] starting explicit solvent openMM simulation with file: None
[<time>libparallel WARNING] Exception in task execution: 'NoneType' object is not iterable
[<time>openmm INFO] Minimizing system energy
[<time>openmm INFO] Minimizing system energy
[<time>openmm INFO] starting explicit solvent openMM simulation with file: None
[<time>libparallel WARNING] Exception in task execution: 'NoneType' object is not iterable
[<time>openmm INFO] starting explicit solvent openMM simulation with file: None
[<time>libparallel WARNING] Exception in task execution: 'NoneType' object is not iterable
[<time>openmm INFO] Minimizing system energy
[<time>openmm INFO] starting explicit solvent openMM simulation with file: None
[<time>libparallel WARNING] Exception in task execution: 'NoneType' object is not iterable
[<time>openmm INFO] Minimizing system energy
[<time>openmm INFO] starting explicit solvent openMM simulation with file: None
[<time>libparallel WARNING] Exception in task execution: 'NoneType' object is not iterable
[<time>libparallel INFO] 9 tasks finished
[<time>libutil ERROR] No output models generated. Check Openmm Execution and logfile.
Traceback (most recent call last):
  File "~miniconda3/envs/haddock_pip/lib/python3.9/site-packages/haddock/libs/libutil.py", line 335, in log_error_and_exit
    yield
  File "~miniconda3/envs/haddock_pip/lib/python3.9/site-packages/haddock/clis/cli.py", line 195, in main
    workflow.run()
  File "~miniconda3/envs/haddock_pip/lib/python3.9/site-packages/haddock/libs/libworkflow.py", line 43, in run
    step.execute()
  File "~miniconda3/envs/haddock_pip/lib/python3.9/site-packages/haddock/libs/libworkflow.py", line 162, in execute
    self.module.run()  # type: ignore
  File "~miniconda3/envs/haddock_pip/lib/python3.9/site-packages/haddock/modules/__init__.py", line 245, in run
    self._run()
  File "~miniconda3/envs/haddock_pip/lib/python3.9/site-packages/haddock/modules/refinement/openmm/__init__.py", line 164, in _run
    self.finish_with_error(
  File "~miniconda3/envs/haddock_pip/lib/python3.9/site-packages/haddock/modules/__init__.py", line 317, in finish_with_error
    raise RuntimeError(reason)
RuntimeError: No output models generated. Check Openmm Execution and logfile.
```

## **Steps to reproduce the behavior**
Docking two molecules, antibody and antigen with openmm refinement. There is a gap in numbering due to two chains of antibody being merged and restrained ie 1...120...1001-1120. (?cause of error)

## **Suggestions on how to fix it**
I presume this is an issue with  PDB numbering, but the chain linking is per the haddock tutorial. Should there be a way to renumber and rechain the protein e.g. with pdb_tools, before running openmm?

## **Version**
HADDOCK3 v2024.10.0b6 on 2024-11-19 11:06:00
