### ISSUE TITLE
DockQ scores show NaN values with new peptide-protein inputs despite correct setup

### ISSUE THREAD

**Issue by jwframe28** [haddocking/haddock3#1249]
I am running peptide-protein ab initio docking with Haddock3, and my newest runs are having nan values in the DockQ column (as well as a few others).

In the stdout, it mentions something about "No reference structure" being found, but when I've run the code with the same .cfg file in the past, I've received results.

Is there something that typically causes this? I am using a different peptide and protein .pdb file for input than I did with my successful earlier run.

The original .cfg (which worked) is below, and provided a strong DockQ score. However, when I alter the molecules to new ones, it does not. 

I had considered that I had not changed the fle_sta_len parameters to be the size of the peptides I'm looking at now, but for one such run (which was the same length), it fails. 

I should also note that for the example below I used Alphafold to produce a .pdb file but in my new runs which are failing I'm using PEP-FOLD3

```toml
# ====================================================================
# protein-peptide docking example

# directory in which the scoring will be done
run_dir = "run4-test"

# execution mode
mode = "local"
ncores = 40

# molecules to be docked
molecules =  [
    "fold_2025_04_07_13_45_model_0_chainB.pdb",
    "AF-P28223-F1-model_v4.pdb"
    ]

# ====================================================================
[topoaa]

[rigidbody]
sampling = 50
ambig_fname = "ambig.tbl"

[flexref]
tolerance = 20
ambig_fname = "ambig.tbl"
# Define peptide as fully flexible
fle_sta_1 = 1
fle_seg_1 = "A"
fle_end_1 = 12

[clustfcc]
min_population = 1

[seletopclusts]
top_models = 4

# ====================================================================
```
