### ISSUE TITLE
list index out of range when using `ambig_fname="ambig.tbl.tgz"` in [flexref] module

### ISSUE THREAD

**Issue by alchemistcai** [haddocking/haddock3#1257]
## **Module/Workflow/Library affected**

Setting `ambig_fname="ambig.tbl.tgz"` in cfg file works for [rigidbody] module.However,[flexref] module is stopped by IndexError.I added a print statement in `flexref/__init__.py` and here is the log:

```log
[2025-04-25 09:09:44,697 base_cns_module INFO] Running [flexref] module
[2025-04-25 09:09:44,698 __init__ INFO] [flexref] Searching for ambig*tbl files in ../data/5_flexref
[2025-04-25 09:09:44,698 __init__ INFO] [flexref] Found 20 compatible tbl files
`ambig_fname` size:20,`models_to_refine` size:369
[2025-04-25 09:09:45,019 libutil ERROR] list index out of range
Traceback (most recent call last):
.......
  File "/home/regen/ana/envs/haddock3/lib/python3.9/site-packages/haddock/modules/base_cns_module.py", line 61, in run
    self._run()
  File "/home/regen/ana/envs/haddock3/lib/python3.9/site-packages/haddock/modules/refinement/flexref/__init__.py", line 107, in _run
    ambig_fname = ambig_fnames[model_idx]
IndexError: list index out of range
[2025-04-25 09:09:45,020 libutil ERROR] list index out of range
```

## **Expected behavior**

I defined 20 possible pocket restraint tbl files in `ambig.tbl.tgz`,they are evenly assigned to each inp file in [rigidbody] module.After [clustfcc] and [seletopclusts] ,each complex in  [flexref] should know its corresponding ambig_fname before.

## **Actual behavior**

Defining `ambig_fname="ambig.tbl.tgz"` leads to IndexError.In my case,there are 20 ambig*tbl and 369 complexes in [flexref] module,leading to IndexError.

## **Steps to reproduce the behavior**

Here  is my cfg file for protein-ligand docking:

```toml
run_dir = "usp9x-atr"
mode = "local"
ncores = 30
debug = "on"
molecules =  [
    "7yxy.pdb",
    "ATRs.pdb",
    ]

[topoaa]
log_level = 'verbose'
ligand_param_fname = "ligand.par"
ligand_top_fname = "ligand.top"
delenph = false

[rigidbody]
tolerance = 5
cmrest = True
cmtight = False
ligand_param_fname = "ligand.par"
ligand_top_fname = "ligand.top"
ambig_fname="ambig.tbl.tgz"  # works for rigidbody
inter_rigid = 0.001
w_vdw = 0.0
sampling = 1000
randremoval = false
mol_fix_origin_1 = true # fix 7yxy,rotate /translate drug

[clustfcc]

[seletopclusts]
top_clusters=50

[caprieval]

[flexref]
tolerance = 5
ligand_param_fname = "ligand.par"
ligand_top_fname = "ligand.top" 
ambig_fname="ambig.tbl.tgz" # multiple tbl definition leads to IndexError in [flexref]
randremoval = false
mol_fix_origin_1 = true

[caprieval]
[clustfcc]
[caprieval]
```

## **Suggestions on how to fix it**

In `rigidbody/__init__.py`,the index is calculate by sampling idx mod ambiguous tbl file numbers:

```py
prev_ambig_fnames = [None for model in range(self.params["sampling"])]
diff_ambig_fnames = self.get_ambig_fnames(prev_ambig_fnames)  # type: ignore
ambig_fnames = [diff_ambig_fnames[n % n_diffs] for n in range(self.params["sampling"])]
```

As we usually don't care which ambig file is used in rigidbody step,this makes sense.

How ever,in [flexref code](https://github.com/haddocking/haddock3/blob/fc7d224d0c4f05fd1cd424a084db11927193df7f/src/haddock/modules/refinement/flexref/__init__.py#L94),this line just collect 20 tbl files from `ambig.tbl.tgz` and leads to IndexError.

This method may need a different version to collect detailed ambig file used by prev_ambig_fnames.

```py
        ambig_fnames = self.get_ambig_fnames(prev_ambig_fnames)
```

[emref] and [mdref] modules are not tested,but they have same code snippets.

In `examples/docking-multiple-ambig`,the cfg file only use multiple ambig files in [rigidbody] step. This may need to be modified.

## **Version**

commit hash: 938f85e93d5a9116938ad808b11e31e465e3aa70
