### ISSUE TITLE
Disulfite bond

### ISSUE THREAD

**Issue by LiviaPham** [haddocking/haddock3#1259]
Hi,
Can you tell me the mechanism of cysteine ​​selection for disulfite bridge formation in haddock3?
Thanks for your support.

**Comment by amjjbonvin** [comment]
It is based on distance between the Sulphur atoms. All CYS-CYS combinations are evaluated.

There is a parameter for the `topoaa` module defining it. The default distance is 2.2A

```
disulphide_dist:
  default: 2.20
  type: float
  precision: 2
  min: 0.00
  max: 999999.99
  title: Cutoff distance for S-S bonds
  short: Cutoff distance in Angstroms for identification of disulphide bonds
  long: Cutoff distance in Angstroms for identification of disulphide bonds (SH - SH)
  group: molecule
  explevel: guru
```

Note that for this kind of questions you can also use the HADDOCK forum at ask.bioexcel.eu instead of opening an issue.
