### ISSUE TITLE
States of termini residues

### ISSUE THREAD

**Issue by VGPReys** [haddocking/haddock3#1269]
## **Desired feature/enhancement**

In Haddock2.X series, we can select the state of termini residues (Charged/Uncharged Nter-Cter)
For now this cannot be performed in haddock3.

## **Motivation**

It is important to be able to control this behavior.

## **Description**

Add new parameters in `topoaa`, as molecule parameters, to handle these cases:

```TOML
[topoaa]
[topoaa.mol1]
charged_nter = true
charged_cter = false
[topoaa.mol2]
charged_nter = false
charged_cter = true
```

## **Additional context**

Can (should) also be updated for DNA phosphate groups 5' !
