### ISSUE TITLE
Haddock3 did not generate a complex pdb file by docking two pdb files

### ISSUE THREAD

**Issue by 187357181** [haddocking/haddock3#1282]
The cfg configuration file is as follows：

```toml
clean = False 
run_dir = "haddock_run"
ncores = 40
mode = "local"


molecules = [
    "data/23.pdb",
    "data/IRS1under.pdb"
]

[topoaa]
autohis = True  
tolerance = 0.5   

[rigidbody]
sampling = 200
cmrest = True

[seletop]
select = 40

[flexref]
sampling_factor = 10

[emref]
hbond_fname = "complex_haddock.pdb"  # 显式指定输出名
ambig_fname = "data/ambig.tbl"

[caprieval]
```
