### ISSUE TITLE
Multiple calls of same module not being executed

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#149]
Running with this configuration file:

```toml
# ====================================================================
# Rigid-body docking example

# directory in which the scoring will be done
run_dir = "run1"
ncores = 20
# cns_exec = "path/to/bin/cns" # optional

# molecules to be docked
molecules =  [
    "./data/e2aP_1F3G.pdb",
    "./data/hpr_ensemble_1.pdb"
    ]

# ====================================================================
# Parameters for each stage are defined below, prefer full paths
#####################################################################
# WARNING: THE PARAMETERS HERE ARE ILLUSTRATIVE
#  THE WORKFLOW IS WORK-IN-PROGRESS
#####################################################################
[topoaa]
autohis = true

[rigidbody]
ambig_fname = './data/e2a-hpr_air.tbl'
sampling = 20
noecv = true

[caprieval]
reference = './data/e2a-hpr_1GGR.pdb'

[seletop]
select = 5

[flexref]
ambig_fname = './data/e2a-hpr_air.tbl'
noecv = true

[caprieval]
reference = './data/e2a-hpr_1GGR.pdb'

[emref]
ambig_fname = './data/e2a-hpr_air.tbl'
noecv = true

[caprieval]
reference = './data/e2a-hpr_1GGR.pdb'
```
results in:
```
run1
> 00_topoaa
> 01_rigidbody
> 02_caprieval
> 03_seletop
> 04_flexref
> 05_emref
```

Instead of:
```
> 00_topoaa
> 01_rigidbody
> 02_caprieval
> 03_seletop
> 04_flexref
> 05_caprieval
> 06_emref
> 07_caprieval
```
