### ISSUE TITLE
title/descriptions for expandable parameters

### ISSUE THREAD

**Issue by sverhoeven** [haddocking/haddock3#370]
**Is your feature request related to a problem? Please describe.**

Expandable parameters (aka parameters in defaults.yaml files with `_1` in their name) in the [workflow builder](https://github.com/i-VRESSE/workflow-builder) app are rendered as an array of sub forms.

In the builder I generate
```yaml
mol_shape:
  type: array
  items:
    default: false
    title: Is the molecule a shape?
    description: Defines a molecule as a shape.
    $comment: Defines a molecule as a shape, which is a collection of beads.
    type: boolean
```
from a defaults.yaml in haddock3
```yaml
mol_shape_1:
  default: false
  type: boolean
  title: Is the molecule a shape?
  short: Defines a molecule as a shape.
  long: Defines a molecule as a shape, which is a collection of beads. 
  group: 'molecule'
  explevel: easy
```
So `mol_shape.items` has a title, but `mol_shape` itself does not.

I would like to have something like
```yaml class:"lineNo"
mol_shape:
  type: array
  title: Which molecules are a shape?
  description: Defines some molecules as a shape.
  $comment: Defines some molecules as a shape.
  items:
    default: false
    title: Is the molecule a shape?
    description: Defines a molecule as a shape.
    $comment: Defines a molecule as a shape, which is a collection of beads.
    type: boolean
```
Currently there is no place where I can get value of `mol_shape.title`, `mol_shape.description` and `mol_shape.$comment`.

**Describe the solution you'd like**

Somewhere in the haddock3 code to define title/short/long for the parameter in its collapsed state.
This could be done as additional keys in defaults.yaml like

```yaml
mol_shape_1:
  default: false
  type: boolean
  title: Is the molecule a shape?
  short: Defines a molecule as a shape.
  long: Defines a molecule as a shape, which is a collection of beads. 
  expandedtitle: Which molecules are a shape?
  expandedshort: Defines some molecules as a shape.
  expandedlong: Defines some molecules as a shape.
  group: 'molecule'
  explevel: easy
```

However this solution only works nicely for [type 3 expandable parameters](https://github.com/haddocking/haddock3/blob/main/src/haddock/gear/expandable_parameters.py#L57-L65)

**Describe alternatives you've considered**

* For array of scalars (eg. mol_shape_1):  Appending `s` to title of array item. 
* For array of array of objects (eg. rair_sta_1_1 + rair_end_1_1): Find overlap between titles and use that as title for array.
* Use number field with replace (eg. `nfle1.title.replace('Number of', '')`), however these will disappear in fix for #369 

**Additional context**

Below is a screenshot of the app. Instead of `mol_shape` I would like to show a human readable title.
![localhost_3000_ (5)](https://user-images.githubusercontent.com/1713488/161571769-ad98b364-8e63-481e-b531-62924c62af91.png)
