### ISSUE TITLE
check values in cfg files against .yaml files   

### ISSUE THREAD

**Issue by mgiulini** [haddocking/haddock3#487]
currently, values of parameters defined in modules of cfg files are not checked. For example, if there are have many `choices` for a parameter in the yaml file, the code never checks that the value in the cfg file is part of the list present in the corresponding `defaults.yaml` file.

example from clustrmsd:
```
criterion:
  default: "maxclust"
  type: "string"
  ...
  choices:
  - distance
  - maxclust
```
Discussed with @joaomcteixeira.

Related to #333
