### ISSUE TITLE
`validate_parameters_are_not_incompatible` ignoring incompatible value

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#986]
## **Module/Workflow/Library affected**

`gear.prepare_run`

## **Expected behavior**

When reading the incompatible parameter, it should check what is the value that raises the incompatibility

## **Actual behavior**

It does not check the value and breaks the execution

## **Steps to reproduce the behavior**

Run a workflow with the following `toml` file:

```toml
run_dir = "validate-bug"
mode = "batch"
concat = 1
queue_limit = 100
molecules =  [
    "data/e2aP_1F3G.pdb",
    "data/hpr_ensemble.pdb"
    ]
[topoaa]
```

## **Suggestions on how to fix it**

Add a new `value` property to signal which is the value that raises the incompatibility

## **Version**

`2d2f02f38c08c5c1cb41869f99851b8c29974749`
